[package]
name = "cubesrv"
version = "0.1.0"
edition = "2024"

[package.metadata.trueos-blueprint]
replicatable = true

[[bin]]
name = "cubesrv"
path = "server.rs"

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
trueos = { workspace = true, features = ["lifecycle-net"] }

[target.'cfg(any(target_os = "trueos", target_os = "zkvm"))'.dependencies]
trueos-redb.workspace = true

[target.'cfg(not(any(target_os = "trueos", target_os = "zkvm")))'.dependencies]
trueos-redb = { path = "../../crates/trueos-redb", features = ["std"] }
