[package]
name = "veloren_executor"
version = "0.1.0"
edition = "2024"

[package.metadata.trueos-blueprint.build-env-paths]
CARGO_WORKSPACE_DIR = "../../../veloren"

[workspace]
resolver = "3"

[features]
cooperative-worldgen = []

[dependencies]
trueos = { path = "../../api" }
tokio = { version = "=1.52.3", default-features = false, features = ["rt-multi-thread", "time", "sync", "net"] }
tokio-parallel = { package = "veloren-tokio-parallel", path = "../../../veloren/common/tokio-parallel" }
specs = { path = "../../../veloren/vendor/specs" }

[patch.crates-io]
shred = { path = "../../../veloren/vendor/shred" }
hibitset = { path = "../../../veloren/vendor/hibitset" }
