[package]
name = "wc3"
version = "0.1.0"
edition = "2024"

[package.metadata.trueos-blueprint]
replicatable = false

[[bin]]
name = "wc3"
path = "src/main.rs"
test = false
bench = false

[features]
default = ["trace-seh"]
nolog = []
host-memmove = []
replay-loops = []
trace-scan = []
trace-seh = []
trace-api = []
trace-init = []
trace-all = ["trace-scan", "trace-seh", "trace-api", "trace-init"]

[dependencies]
sha2 = "=0.10.9"
tokio = { workspace = true, features = ["rt", "sync", "time"] }
trueos = { path = "../../api", features = ["tokio-runtime", "ui4-scene", "wc3-x86"] }

[dev-dependencies]
pretty_assertions.workspace = true
