[package]
name = "hyper"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[package.metadata.trueos-blueprint]
replicatable = false
entry-abi = "argv-v1"
fs-scope = "trueosfs"

[[bin]]
name = "hyper"
path = "src/main.rs"

[dependencies]
reqwest = { version = "=0.13.3", default-features = false, features = ["rustls"] }
trueos = { path = "../../api", features = ["tokio-net-probe"] }
