[package]
name = "framework_stack"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "framework_stack"
path = "main.rs"

[dependencies]
hyper.workspace = true
mio = { version = "=1.2.0", default-features = false, features = ["os-poll", "net"] }
reqwest = { workspace = true, features = ["rustls"] }
socket2 = { version = "=0.6.3", default-features = false }
tower.workspace = true
trueos.workspace = true
