// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: /home/t4ce/Repos/TRUEOS-Blueprints/apps/shadertoy/assets/cosmic_strands/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_cosmic_strands.d","-MT","shadertoy_cosmic_strands.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_cosmic_strands.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_cosmic_strands.bc","-o","$OUT_DIR/shadertoy_cosmic_strands.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_cosmic_strands.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_cosmic_strands","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_cosmic_strands.bin"]]

pub(crate) const SHADERTOY_COSMIC_STRANDS_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_cosmic_strands",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x9a, 0x27, 0x5f, 0x03, 0x6d, 0xea, 0xc2, 0x74,
        0x54, 0x1a, 0x34, 0x25, 0x6c, 0x09, 0x14, 0x0e,
        0xcd, 0x3f, 0x98, 0xe3, 0x92, 0xc4, 0x96, 0x3a,
        0x27, 0xe6, 0xac, 0x1d, 0xb5, 0xb8, 0x25, 0x00,
    ],
    spv_sha256: [
        0x76, 0x00, 0x79, 0xe1, 0x19, 0xdf, 0x2b, 0x46,
        0xce, 0x0d, 0xb0, 0x1e, 0x09, 0xb6, 0xab, 0x8c,
        0x10, 0x16, 0x48, 0x5c, 0x0f, 0x64, 0x50, 0xba,
        0xc9, 0x22, 0x78, 0xfe, 0xcf, 0x3e, 0x49, 0x77,
    ],
    text_section_name: ".text.shadertoy_cosmic_strands",
    text_section_offset: 64,
    text_section_size: 27200,
    entry_offset: 64,
    entry_size: 27064,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
