[package]
name = "prismq"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "prismq"
path = "main.rs"

[dependencies]
axum.workspace = true
prism-q.workspace = true
rayon.workspace = true
rusqlite_fork = { package = "rusqlite", git = "https://github.com/t4ce/rusqlite", rev = "c5a9ada73515cd860f490f8bdd59f83acf5d8e3f", default-features = false, features = ["bundled", "serialize"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[target.'cfg(any(target_os = "trueos", target_os = "zkvm"))'.dependencies]
trueos.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("trueos", "zkvm"))'] }
