// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: /home/t4ce/Repos/TRUEOS-Blueprints/apps/shadertoy/assets/palette_grid/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_palette_grid.d","-MT","shadertoy_palette_grid.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_palette_grid.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_palette_grid.bc","-o","$OUT_DIR/shadertoy_palette_grid.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_palette_grid.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_palette_grid","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file","-options","-cl-fast-relaxed-math"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_palette_grid.bin"]]

pub(crate) const SHADERTOY_PALETTE_GRID_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_palette_grid",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x0e, 0xd4, 0x56, 0x60, 0xc5, 0xa2, 0x4a, 0x23,
        0x68, 0x67, 0xbe, 0xb8, 0xdb, 0x33, 0x4c, 0x04,
        0x50, 0x12, 0xae, 0x48, 0x46, 0x54, 0x70, 0x9c,
        0x0a, 0x04, 0xbc, 0x98, 0x52, 0xe2, 0x25, 0xd0,
    ],
    spv_sha256: [
        0x59, 0x74, 0x44, 0xe6, 0xe0, 0xa8, 0xe7, 0xb2,
        0x1e, 0x21, 0x33, 0xeb, 0x47, 0x75, 0xd1, 0x84,
        0xa7, 0x3b, 0xfe, 0x95, 0xbe, 0x7c, 0x28, 0xf5,
        0xd3, 0x5c, 0x99, 0x2e, 0x23, 0xe5, 0x0d, 0x07,
    ],
    text_section_name: ".text.shadertoy_palette_grid",
    text_section_offset: 64,
    text_section_size: 2304,
    entry_offset: 64,
    entry_size: 2144,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
