// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: /home/t4ce/Repos/TRUEOS-Blueprints/apps/shadertoy/assets/palette_grid/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_palette_grid.d","-MT","shadertoy_palette_grid.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_palette_grid.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_palette_grid.bc","-o","$OUT_DIR/shadertoy_palette_grid.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_palette_grid.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_palette_grid","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_palette_grid.bin"]]

pub(crate) const SHADERTOY_PALETTE_GRID_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_palette_grid",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x98, 0xa5, 0xa3, 0x91, 0x54, 0xa9, 0x02, 0x1e,
        0x2e, 0x09, 0x40, 0x7c, 0x51, 0x88, 0x64, 0x4a,
        0xc7, 0x44, 0xee, 0xda, 0xe4, 0x03, 0x1e, 0xfd,
        0xf3, 0x95, 0xf6, 0x61, 0x9b, 0x32, 0xfd, 0x40,
    ],
    spv_sha256: [
        0xf6, 0xfd, 0xb5, 0x48, 0xea, 0xb6, 0x33, 0xd5,
        0xac, 0x5d, 0x13, 0x6e, 0x6d, 0xf6, 0xe7, 0x21,
        0x3a, 0x56, 0xc7, 0x93, 0x6a, 0x79, 0x54, 0x89,
        0x37, 0x4e, 0xb2, 0x46, 0x53, 0xfa, 0xf1, 0x97,
    ],
    text_section_name: ".text.shadertoy_palette_grid",
    text_section_offset: 64,
    text_section_size: 35200,
    entry_offset: 64,
    entry_size: 35048,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
