// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: bld/shadertoy-blueprint-bake/sources/protean_clouds/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_protean_clouds.d","-MT","shadertoy_protean_clouds.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_protean_clouds.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_protean_clouds.bc","-o","$OUT_DIR/shadertoy_protean_clouds.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_protean_clouds.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_protean_clouds","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file","-options","-cl-fast-relaxed-math"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_protean_clouds.bin"]]

pub(crate) const SHADERTOY_PROTEAN_CLOUDS_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_protean_clouds",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0xaa, 0xd7, 0x5d, 0x1a, 0xcb, 0x31, 0xae, 0x06,
        0x54, 0x20, 0xee, 0x90, 0x7d, 0x5c, 0x2b, 0xcb,
        0xe9, 0xbb, 0x73, 0xb7, 0x1f, 0x29, 0xc2, 0x79,
        0x43, 0xa0, 0xec, 0x15, 0x04, 0x95, 0x6e, 0x56,
    ],
    spv_sha256: [
        0x2b, 0x8c, 0x0b, 0x34, 0x3a, 0xf4, 0xf0, 0x80,
        0x0a, 0xac, 0x42, 0xd3, 0x75, 0x41, 0xb0, 0x5f,
        0x16, 0x2e, 0x34, 0xf0, 0xe8, 0xf4, 0xb8, 0xab,
        0x24, 0xb4, 0x54, 0xf8, 0x25, 0xe2, 0xc4, 0xb6,
    ],
    text_section_name: ".text.shadertoy_protean_clouds",
    text_section_offset: 64,
    text_section_size: 20544,
    entry_offset: 64,
    entry_size: 20416,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
        GpgpuArtifactBinding { arg_index: 5, bti: 2 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 76, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 80, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 5, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 64, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateful },
    ],
};
