// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: bld/shadertoy-blueprint-bake/sources/protean_clouds/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_protean_clouds.d","-MT","shadertoy_protean_clouds.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_protean_clouds.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_protean_clouds.bc","-o","$OUT_DIR/shadertoy_protean_clouds.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_protean_clouds.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_protean_clouds","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_protean_clouds.bin"]]

pub(crate) const SHADERTOY_PROTEAN_CLOUDS_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_protean_clouds",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x42, 0x70, 0x81, 0x49, 0xdf, 0xf2, 0x8c, 0x43,
        0xdf, 0x0c, 0xc2, 0xbd, 0xd4, 0x14, 0x71, 0x69,
        0xae, 0xc9, 0x3e, 0xca, 0xbb, 0xc0, 0x03, 0x12,
        0x2c, 0x1e, 0x76, 0xa5, 0xb0, 0x0b, 0x7c, 0xbc,
    ],
    spv_sha256: [
        0xb9, 0xa7, 0x6a, 0xe7, 0xea, 0x1b, 0x83, 0x4d,
        0xb6, 0x21, 0x66, 0x30, 0xfd, 0x37, 0x0f, 0xdf,
        0x2d, 0xaa, 0x12, 0x3c, 0x47, 0xb3, 0x27, 0x49,
        0x10, 0xbd, 0x26, 0xdf, 0x24, 0x3f, 0x42, 0xfd,
    ],
    text_section_name: ".text.shadertoy_protean_clouds",
    text_section_offset: 64,
    text_section_size: 220224,
    entry_offset: 64,
    entry_size: 220064,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
