// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: bld/shadertoy-blueprint-bake/sources/mandelbrot/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_mandelbrot.d","-MT","shadertoy_mandelbrot.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_mandelbrot.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_mandelbrot.bc","-o","$OUT_DIR/shadertoy_mandelbrot.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_mandelbrot.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_mandelbrot","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_mandelbrot.bin"]]

pub(crate) const SHADERTOY_MANDELBROT_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_mandelbrot",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x79, 0xe5, 0x66, 0xad, 0x2d, 0xb0, 0x1a, 0x1a,
        0x24, 0x67, 0xe0, 0x28, 0x9b, 0xd9, 0x7e, 0x9c,
        0x77, 0xc6, 0x7b, 0xe7, 0xbd, 0x4a, 0x59, 0xd9,
        0x57, 0xda, 0xdd, 0x84, 0xe0, 0xec, 0x32, 0xd1,
    ],
    spv_sha256: [
        0xee, 0x7a, 0xb8, 0x0d, 0x47, 0x2a, 0xc9, 0x45,
        0x7c, 0xa3, 0x7d, 0x36, 0xfa, 0x34, 0x41, 0x02,
        0x01, 0x82, 0xfa, 0x37, 0x89, 0xf4, 0x99, 0xc9,
        0x50, 0x30, 0xec, 0x2f, 0x69, 0xa9, 0xea, 0x34,
    ],
    text_section_name: ".text.shadertoy_mandelbrot",
    text_section_offset: 64,
    text_section_size: 5440,
    entry_offset: 64,
    entry_size: 5304,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
