[build]
target = "x86_64-unknown-linux-gnu"
target-dir = "target"

[unstable]
build-std = ["std", "core", "alloc", "panic_abort"]

[alias]
bp = "run --bin trueos-blueprint --"
bpp = "run --bin trueos-blueprint -- --probes"
apps = "run --bin trueos-blueprint --"
