[package]
name = "exp"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "exp"
path = "src/main.rs"
test = false
bench = false

[dependencies]
crossterm = { version = "0.29", default-features = false }

[target.'cfg(any(target_os = "trueos", target_os = "zkvm"))'.dependencies]
trueos = { path = "../../api" }
