[package]
name = "rusqlite_probe"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rusqlite_probe"
path = "main.rs"

[dependencies]
rusqlite_fork = { package = "rusqlite", git = "https://github.com/t4ce/rusqlite", rev = "c5a9ada73515cd860f490f8bdd59f83acf5d8e3f", default-features = false, features = ["bundled", "serialize"] }
trueos.workspace = true
