#![cfg(feature = "trueos")]

pub(crate) struct EmbeddedModule {
    pub(crate) path: &'static [u8],
    pub(crate) src: &'static [u8],
    pub(crate) bytecode: &'static [u8],
}

// Generated by build.rs (scans this crate's src/**/*.mjs).
// Defines: `static EMBEDDED: &[EmbeddedModule]`.
include!(concat!(env!("OUT_DIR"), "/embedded_qjs/embedded_modules.rs"));

#[inline]
pub(crate) fn find(path: &[u8]) -> Option<&'static EmbeddedModule> {
    // Linear scan is fine at this scale.
    for m in EMBEDDED {
        if m.path == path {
            return Some(m);
        }
    }
    None
}
