[package]
name = "template-terminal-in-out"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "template-terminal-in-out"
path = "src/main.rs"
test = false
bench = false

[dependencies]
trueos = { path = "../../api" }

[workspace]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("trueos", "zkvm"))'] }
