[package]
name = "img"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
[package.metadata.trueos-blueprint]
replicatable = true

[[bin]]
name = "img"
path = "src/main.rs"
test = false
bench = false

[dependencies]
trueos = { workspace = true, features = ["ui4-scene"] }
miniz_oxide = { version = "0.9.1", default-features = false, features = ["with-alloc"] }
crc32fast = { version = "1.5.0", default-features = false }
jpeg-encoder = { version = "=0.7.1", default-features = false }
