[package]
name = "gridpaper"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[package.metadata.trueos-blueprint]
replicatable = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "gridpaper"
path = "src/main.rs"
test = false
bench = false

[dependencies]
trueos = { workspace = true, features = ["ui4-scene"] }
