[package]
name = "v"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
hashbrown = { version = "0.17", default-features = false, features = ["default-hasher", "serde"] }
spin = "0.10"
skrifa = { version = "0.44.0", default-features = false, features = ["libm"] }
serde = { version = "=1.0.228", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "=1.0.150", default-features = false, features = ["alloc"] }
trueos-math = { path = "../trueos-math", default-features = false }

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("trueos", "zkvm"))'] }
