[package]
name = "trueos"
version = "0.1.0"
edition = "2024"

[features]
default = []
default-global-allocator = []
default-panic-handler = []
tokio-runtime = []
tokio-net-probe = ["dep:mio", "dep:socket2", "tokio/net"]
ui2 = []

[lib]
name = "trueos"
path = "src/lib.rs"

[dependencies]
v = { path = "../../TRUEOS/crates/trueos-v" }
tokio = { path = "../../TRUEOS/vendor/tokio-1.52.3", default-features = false, features = ["rt", "macros", "sync", "time", "io-util", "io-std", "fs"] }
mio = { path = "../../TRUEOS/vendor/mio-1.2.0", default-features = false, features = ["os-poll", "net"], optional = true }
socket2 = { path = "../../TRUEOS/vendor/socket2-0.6.3", default-features = false, optional = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("trueos", "zkvm"))'] }
