// @generated by tools/intel-gpu-bakery; DO NOT EDIT.
// source: bld/shadertoy-blueprint-bake/sources/cube_field/kernel.clcpp
// frontend: Clang C++ for OpenCL -> LLVM bitcode -> llvm-spirv
// backend: Intel IGC through ocloc -spirv_input
// normalized commands: [["$CLANG","--target=spir64","-x","clcpp","-cl-std=CLC++","-Wall","-Wextra","-Werror","-Wdate-time","-cl-kernel-arg-info","-fno-discard-value-names","-fno-exceptions","-fno-rtti","-MMD","-MF","$OUT_DIR/shadertoy_cube_field.d","-MT","shadertoy_cube_field.bc","-emit-llvm","-c","kernel.clcpp","-o","$OUT_DIR/shadertoy_cube_field.bc"],["$LLVM_SPIRV","--preserve-ocl-kernel-arg-type-metadata-through-string","$OUT_DIR/shadertoy_cube_field.bc","-o","$OUT_DIR/shadertoy_cube_field.spv"],["$OCLOC","compile","-file","$OUT_DIR/shadertoy_cube_field.spv","-spirv_input","-device","0x4680","-64","-output","shadertoy_cube_field","-out_dir","$OUT_DIR","-output_no_suffix","-gen_file"],["$OCLOC","validate","-file","$OUT_DIR/shadertoy_cube_field.bin"]]

pub(crate) const SHADERTOY_CUBE_FIELD_ADLS_CPP_ABI_CONTRACT: GpgpuKernelAbiContract = GpgpuKernelAbiContract {
    schema_version: GPGPU_KERNEL_ABI_SCHEMA_VERSION,
    kernel_name: "shadertoy_cube_field",
    target: GpgpuKernelTarget {
        label: "adls",
        pci_device_ids: &[0x4680],
        revision_min: 12,
        revision_max: 12,
    },
    ze_info_major: 1,
    ze_info_minor: 62,
    zebin_sha256: [
        0x04, 0xf9, 0x40, 0xae, 0x84, 0x74, 0x69, 0x75,
        0xd6, 0xc1, 0x10, 0x33, 0xce, 0x78, 0x99, 0xcc,
        0xc8, 0x30, 0x7b, 0xad, 0xca, 0xf3, 0x09, 0x1f,
        0x53, 0xa6, 0x54, 0xca, 0x10, 0x25, 0x6f, 0x10,
    ],
    spv_sha256: [
        0x50, 0x41, 0xf1, 0x3b, 0x86, 0xf7, 0xf8, 0x48,
        0x0a, 0xed, 0x9e, 0x1c, 0x69, 0x66, 0x40, 0xe2,
        0x5a, 0x9b, 0xe8, 0x80, 0xc0, 0xfc, 0x7b, 0xd8,
        0x6c, 0x84, 0x9e, 0x0a, 0x5f, 0xba, 0x79, 0x4a,
    ],
    text_section_name: ".text.shadertoy_cube_field",
    text_section_offset: 64,
    text_section_size: 36928,
    entry_offset: 64,
    entry_size: 36760,
    simd_width: 16,
    grf_count: 128,
    scratch_bytes: 0,
    slm_bytes: 0,
    cross_thread_data_bytes: 96,
    per_thread_data_bytes: 96,
    bindings: &[
        GpgpuArtifactBinding { arg_index: 0, bti: 0 },
        GpgpuArtifactBinding { arg_index: 1, bti: 1 },
    ],
    implicit_payload_args: &[
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::GlobalIdOffset, offset_bytes: 0, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::LocalSize, offset_bytes: 12, size_bytes: 12 },
        GpgpuArtifactImplicitPayloadArg { kind: GpgpuArtifactImplicitArgKind::EnqueuedLocalSize, offset_bytes: 32, size_bytes: 12 },
    ],
    per_thread_payload_args: &[
        GpgpuArtifactPerThreadPayloadArg { kind: GpgpuArtifactPerThreadArgKind::LocalId, offset_bytes: 0, size_bytes: 96 },
    ],
    payload_args: &[
        GpgpuArtifactPayloadArg { arg_index: 0, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 48, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadWrite, address_mode: GpgpuArtifactAddressMode::Stateful },
        GpgpuArtifactPayloadArg { arg_index: 1, kind: GpgpuArtifactArgKind::ByPointer, offset_bytes: 56, size_bytes: 8, access: GpgpuArtifactArgAccess::ReadOnly, address_mode: GpgpuArtifactAddressMode::Stateless },
        GpgpuArtifactPayloadArg { arg_index: 2, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 64, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 3, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 68, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
        GpgpuArtifactPayloadArg { arg_index: 4, kind: GpgpuArtifactArgKind::ByValue, offset_bytes: 72, size_bytes: 4, access: GpgpuArtifactArgAccess::None, address_mode: GpgpuArtifactAddressMode::None },
    ],
};
